import type { ReactNode } from 'react';
import type { Metadata } from 'next';
import { Theme, Box, Flex } from '@radix-ui/themes';
import { Sidebar } from '@/widgets/Sidebar';
import { Header } from '@/widgets/Header';
import localFont from 'next/font/local';
import '@radix-ui/themes/styles.css';
import '@/styles/global.scss';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});

const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Theme>
          <Header />
          <Flex>
            <Sidebar />
            <main className="layout-main">
              <Box style={{ width: '100%', maxWidth: '56.25rem' }}>
                {children}
              </Box>
            </main>
          </Flex>
        </Theme>
      </body>
    </html>
  );
}
