import { JsonLde } from '@/widgets/Tools/JsonLde';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'JSON+LDE Converter',
  description: 'Generated by create next app',
};

export default function page() {
  return (
    <main>
      <JsonLde />
    </main>
  );
}
